name: Lint Awesome List
on: [push, pull_request]
  paths-ignore:
    - android/*
    - ios/*
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: max/awesome-lint@v2.0.0
