---
name: Lint Awesome Actions

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions: read-all

jobs:
  build:
    name: Lint Awesome Actions
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Lint Awesome Actions
        uses: super-linter/super-linter@v7
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_MARKDOWN_PRETTIER: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
